---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  CF_API_URL:
  CF_CLIENT_IP:
  CF_UAA_URL:
  CF_APPS_DOMAIN_NAME:

inputs:
  - name: homelab

run:
  path: homelab/pipelines/install-kubo/tasks/config-pcf/task.sh
