---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  KUBO_SERVICE_NAME:
  PCF_SYSTEM_DOMAIN:
  PCF_USERNAME:
  PCF_PASSWORD:

inputs:
  - name: homelab
  - name: environment-state

run:
  path: homelab/pipelines/install-kubo/tasks/config-pcf/task.sh
