---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  ROUTING_MODE:
  KUBERNETES_MASTER_HOST:
  KUBERNETES_MASTER_PORT:
  PCF_API_URL:
  PCF_CLIENT_IP:
  PCF_UAA_URL:
  PCF_APPS_DOMAIN_NAME:
  PCF_NATS_INTERNAL_IPS:
  PCF_NATS_USERNAME:
  PCF_NATS_PASSWORD:
  PCF_NATS_PORT:

inputs:
  - name: homelab
  - name: kubo-environment

run:
  path: homelab/pipelines/install-kubo/tasks/config-router/task.sh
