---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:


inputs:
  - name: homelab
  - name: kubo-deployment
  - name: kubo-environment

run:
  path: homelab/pipelines/install-kubo/tasks/deploy-k8s/task.sh
