# pipeline configuration
iaas: vsphere

# vCenter configuration
vcenter-host:             ((vcenter-host))          # vCenter host or IP
vcenter-datacenter:       ((vcenter-datacenter))    # vCenter datacenter
vcenter-cluster:          ((vcenter-cluster))

# state management in github
state-repository:         ((git-server)):((git-user))/((state-repo))
git-user:                 ((git-user))
git-email:                ((git-email))

# Kubo basics
environment-id:           ((env-id))                # environment identifier for this Kubo installation
kubo-director-name:       ((env-id))-kubo-director

# versions
stemcell-version:         "3445.11"
odb-sdk-version:          "0.16.1"

# vCenter Cluster or Resource Pool to use to deploy Kubo.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
kubo-resource-pool: ((vcenter-resource-pool))

# Datastore to use for K8s machines and persistenet volumes
kubo-ephemeral-store:   ((slow-storage))
kubo-persistent-store:  ((slow-storage))

# folders/paths for vCenter
kubo-vm-folder: ((env-id))-kubo-vms
kubo-template-folder: ((env-id))-kubo-templates
kubo-disk-path: ((env-id))-kubo-disks

# network configuration
director-ip:            ((director-ip))              # IP address for the BOSH director
vsphere-network:        ((container-network))        # vCenter Infrastructure network name
network-cidr:           ((container-cidr))           # Infrastructure network CIDR, ex: 10.0.0.0/22
excluded-range:         ((container-excluded))       # Infrastructure network exclusion range
network-dns:            ((dns-server-1))             # Infrastructure network DNS
network-gateway:        ((container-gateway))        # Infrastructure network Gateway

# routing configuration
routing-mode: cf
k8s-master-host: tcp.((subdomain))                               # Hostname of TCP router. Use `cf domains` to find existing TCP domain. If none exists, see https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains for instructions to create one.
k8s-master-port: 1120
pcf-api-url:     https://api.((system-prefix)).((subdomain))     # TCP routing API URL. In PCF: https://api.<system domain>
pcf-uaa-url:     https://uaa.((system-prefix)).((subdomain))     # Routing UAA URL In PCF: https://uaa.<system domain>
pcf-apps-domain:   ((apps-prefix)).((subdomain))             # Cloud Foundry apps domain
pcf-system-domain:   ((system-prefix)).((subdomain))             # Cloud Foundry system domain

pcf-nats-internal-ips:
- ((pcf-nats-internal-ip-1))
- ((pcf-nats-internal-ip-2))
- ((pcf-nats-internal-ip-3))
pcf-nats-port: 4222
