# pipeline configuration

# vCenter configuration
vcenter-host:             ((vcenter-host))          # vCenter host or IP
vcenter-datacenter:       ((vcenter-datacenter))    # vCenter datacenter

# Kubo basics
kubo-environment:         ((env-id))                # environment identifier for this Kubo installation

# vCenter Cluster or Resource Pool to use to deploy Kubo.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
kubo-resource-pool: /((vcenter-data-center))/host/((vcenter-cluster))/Resources/((vcenter-resource-pool-1))

# Datastore to use for K8s machines and persistenet volumes
kubo-datastore:   ((kubo_datastore))

# network configuration
network-name: "INFRASTRUCTURE"
vsphere-network:        ((container-network))        # vCenter Infrastructure network name
network-cidr:           ((container-cidr))           # Infrastructure network CIDR, ex: 10.0.0.0/22
excluded-range:         ((container-excluded))       # Infrastructure network exclusion range
network-dns:            ((dns-servers))         # Infrastructure network DNS
network-gateway:        ((container-gateway))              # Infrastructure network Gateway

# routing configuration
routing_mode: cf
kubernetes_master_host: ((k8s-master-host))                             # Hostname of TCP router. Use `cf domains` to find existing TCP domain. If none exists, see https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html#shared-domains for instructions to create one.
kubernetes_master_port: ((k8s-master-port))                             # Port for kubernetes api-server on HA Proxy master node
routing-cf-api-url:     https://api.((system-domain)).((subdomain))     # TCP routing API URL. In PCF: https://api.<system domain>
routing-cf-client-id:   ((env-id))-kubo                                 # Routing UAA client name that will be used to register tcp routes
routing-cf-uaa-url:     https://uaa.((system-domain)).((subdomain))     # Routing UAA URL In PCF: https://uaa.<system domain>
routing-cf-app-domain-name:   ((apps-domain))                           # Cloud Foundry apps domain
routing-cf-nats-internal-ips: ((pcf-nats-internal-ips))                 # An array of internal IP address of Cloud Foundry NATS, e.g. [ '1.2.3.4' ]
routing-cf-nats-username: nats
routing-cf-nats-port: 4222
