jobs:
- name: prepare-vsphere
  plan:
  - get: homelab
  - task: create-users
    file: homelab/pipelines/install-kubo/tasks/create-users/task.yml
    params:
      GOVC_INSECURE: 1
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_RESOURCE_POOL: ((kubo_resource_pool))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
  - task: create-infrastructure
    file: homelab/pipelines/install-kubo/tasks/create-infrastructure/task.yml
    params:
      GOVC_DATACENTER: ((vcenter_data_center))
      GOVC_DATASTORE: ((kubo_data_store))
      GOVC_HOST: ((kubo_vm_host))
      GOVC_INSECURE: 1
      GOVC_NETWORK: ((kubo_vm_network))
      GOVC_PASSWORD: ((vcenter_pwd))
      GOVC_RESOURCE_POOL: ((kubo_resource_pool))
      GOVC_URL: ((vcenter_host))
      GOVC_USERNAME: ((vcenter_usr))
- name: configure-director
  - get: kubo-deployment
  - task: generate-template
    file: homelab/pipelines/install-kubo/tasks/generate-template/task.yml
    params:
      GOVC_INSECURE:
      GOVC_URL:
      GOVC_USERNAME:
      GOVC_PASSWORD:
      GOVC_DATACENTER:
      GOVC_DATASTORE:
      GOVC_NETWORK:
      GOVC_RESOURCE_POOL:
      GOVC_HOST:
      KUBO_VC_USER:
      KUBO_VC_PASSWORD:
  - task: customize-template
    file: homelab/pipelines/install-kubo/tasks/customize-director/task.yml
    params:
      IAAS:
      VCENTER_IP:
      VCENTER_USER:
      VCENTER_PASSWORD:
      VCENTER_DATACENTER:
      VCENTER_VMS:
      VCENTER_TEMPLATES:
      VCENTER_DISKS:
      VCENTER_DATESTORE:
      VCENTER_CLUSTER:
      VCENTER_RESOURCE_POOL:
  - task: configure-router
    file: homelab/pipelines/install-kubo/tasks/config-router/task.yml
    params:
      ROUTING_MODE:
      KUBERNETES_MASTER_HOST:
      KUBERNETES_MASTER_PORT:
      MASTER_TARGET_POOL:
      NETWORK_NAME:
      RESERVED_IPS:
      CF_API_URL:
      CF_CLIENT_IP:
      CF_UAA_URL:
      CF_APPS_DOMAIN_NAME:
      CF_NATS_INTERNAL_IPS:
      CF_NATS_USERNAME:
      CF_NATS_PORT:
- name: deploy-kubo
  plan:
    - get: homelab
    - task:
      file: homelab/pipelines/install-kubo/tasks/config-kubo/task.yml
    - name: deploy-kubo
      file: homelab/pipelines/install-kubo/tasks/deploy-k8s/task.yml

resources:
  - name: homelab
    type: git
    source:
      uri: https://github.com/crdant/homelab.git
      branch: master
  - name: kubo-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/kubo-deployment.git
      branch: master

resource_types:
