jobs:

- name: configure-director
  plan:
  - get: homelab
  - get: kubo-odb-deployment
  - task: config-director
    file: homelab/pipelines/install-kubo/tasks/config-director/task.yml
    params:
      KUBO_ENV: ((environment-state))
      IAAS: ((iaas))
      VCENTER_HOST: ((vcenter-host))
      VCENTER_USER: ((kubo-vcenter-account.username))
      VCENTER_PASSWORD: ((kubo-vcenter-account.password))
      VCENTER_DATACENTER: ((vcenter-datacenter))
      VCENTER_CLUSTER: ((vcenter-cluster))
      VCENTER_RESOURCE_POOL: ((kubo-resource-pool))
      KUBO_DIRECTOR_NAME: ((kubo-director-name))
      KUBO_VM_FOLDER: ((kubo-vm-folder))
      KUBO_TEMPLATES: ((kubo-template-folder))
      KUBO_DISK_PATH: ((kubo-disk-path))
      KUBO_EPHEMERAL_STORE: ((kubo-ephemeral-store))
      NETWORK_NAME: ((network-name))
      EXCLUDED_RANGE: ((excluded-range))
      GATEWAY: ((network-gateway))
      DNS: ((network-dns))
  - task: config-pcf
    file: homelab/pipelines/install-kubo/tasks/config-pcf/task.yml
    params:
      PCF_API_URL: ((pcf-api-url))
      PCF_CLIENT_ID: ((pcf-client-id))
      PCF_UAA_URL: ((pcf-uaa-url))
      PCF_APPS_DOMAIN: ((pcf-apps-domain))
  - task: config-router
    file: homelab/pipelines/install-kubo/tasks/config-router/task.yml
    params:
      ROUTING_MODE: ((routing-mode))
      KUBERNETES_MASTER_HOST: ((k8s-master-host))
      KUBERNETES_MASTER_PORT: ((k8s-master-port))
      PCF_API_URL: ((pcf-api-url))
      PCF_CLIENT_ID: ((pcf-client-id))
      PCF_UAA_URL: ((pcf-uaa-url))
      PCF_APPS_DOMAIN: ((pcf-apps-domain))
      PCF_NATS_INTERNAL_IPS: ((pcf-nats-internal-ips))
      PCF_NATS_USERNAME: ((pcf-nats.username))
      PCF_NATS_PASSWORD: ((pcf-nats.password))
      PCF_NATS_PORT: ((pcf-nats-port))
  - task: deploy-director
    file: homelab/pipelines/install-kubo/tasks/deploy-director/task.yml
  - put: environment-state


- name: deploy-kubo
  plan:
  - get: homelab
    passed:
    - configure-director
  - get: environment-state
    passed:
    - configure-director
    trigger: true
  - task: config-k8s
    file: homelab/pipelines/install-kubo/tasks/config-k8s/task.yml
  - task: deploy-kubo
    file: homelab/pipelines/install-kubo/tasks/deploy-k8s/task.yml

resources:
  - name: homelab
    type: git
    source:
      uri: https://github.com/crdant/homelab.git
      branch: master
  - name: kubo-odb-deployment
    type: git
    source:
      uri: https://github.com/cloudfoundry-incubator/kubo-deployment.git
      private_key: ((git.private_key))
  - name: environment-state
    type: git
    source:
      uri: ((state-repository))
      private_key: ((git.private_key))

resource_types:
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource
