---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:
  KUBO_VM_NETWORK:

  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_SSH_PWD:
  OM_NTP_SERVERS:
  OM_DNS_SERVERS:
  OM_GATEWAY:
  OM_NETMASK:
  OM_IP:
  OM_VM_NETWORK:
  OM_VM_NAME:
  OM_RESOURCE_POOL:
  OPSMAN_DISK_TYPE:
  OM_VM_POWER_STATE:

inputs:
  - name: homelab

run:
  path: homelab/pipelines/install-kubo/tasks/create-infrastructure/task.sh
