---

platform: linux

image_resource:
  type: docker-image
  source: {repository: starkandwayne/concourse}

params:

inputs:
  - name: homelab
  - name: environment-state
  - name: odb-sdk
  - name: kubo-service-adapter
  - name: kubo-release
  - name: stemcell

outputs:
  - name: odb-releases

run:
  path: homelab/pipelines/install-kubo/tasks/prepare-odb/task.sh
