- type: replace
  path: /resources/-
  value:
    name: homelab
    type: git
    source:
      uri: https://github.com/crdant/homelab.git
      branch: master

- type: replace
  path: /jobs/name=deploy-ert/plan/task=configure/file
  value: homelab/pipelines/install-pcf/tasks/config-srt/task.yml

- type: replace
  path: /jobs/name=deploy-ert/plan/0/aggregate/get=pivnet-product/params
  value:
    globs:
    - srt*.pivotal

- type: replace
  path: /jobs/name=stage-ert/plan/0/aggregate/get=pivnet-product/params
  value:
    globs:
    - srt*.pivotal

- type: replace
  path: /jobs/name=upload-ert/plan/0/aggregate/get=pivnet-product/params
  value:
    globs:
    - srt*.pivotal

- type: replace
  path: /jobs/name=deploy-ert/plan/0/aggregate/-
  value:
    get: homelab
