---

platform: linux

image_resource:
  type: docker-image
  source:
    - repository: starkandwayne/concourse

params:
  GOVC_INSECURE:
  GOVC_URL:
  GOVC_USERNAME:
  GOVC_PASSWORD:
  GOVC_DATACENTER:
  GOVC_DATASTORE:
  GOVC_NETWORK:
  GOVC_RESOURCE_POOL:
  GOVC_HOST:

inputs:
  - name: homelab
  - name: kubo-odb-deployment
  - name: director-config

outputs:
  - name: director-state

run:
  path: homelab/pipelines/install-kubo/tasks/deploy-director/task.sh
