---

platform: linux

image_resource:
  type: docker-image
  source:
    - repository: starkandwayne/concourse

params:
  GIT_USER:
  GIT_EMAIL:

inputs:
  - name: homelab
  - name: kubo-odb-deployment
  - name: environment-state

outputs:
  - name: director-state

run:
  path: homelab/pipelines/install-kubo/tasks/deploy-director/task.sh
