---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  IAAS:
  VCENTER_IP:
  VCENTER_USER:
  VCENTER_PASSWORD:
  VCENTER_DATACENTER:
  VCENTER_VMS:
  VCENTER_TEMPLATES:
  VCENTER_DISKS:
  VCENTER_DATESTORE:
  VCENTER_CLUSTER:
  VCENTER_RESOURCE_POOL:
  ROUTING_MODE:
  KUBERNETES_MASTER_HOST:
  KUBERNETES_MASTER_PORT:
  MASTER_TARGET_POOL:
  NETWORK_NAME:
  RESERVED_IPS:

inputs:
  - name: homelab

run:
  path: homelab/pipelines/install-kubo/tasks/config-director/task.sh
