# Pipeline resource configuration
opsman_major_minor_version: ^2\.0\..*$ # PCF Ops Manager minor version to track
ert_major_minor_version: ^2\.0\..*$ # PCF Elastic Runtime minor version to track

# vCenter configuration
vcenter_host:             ((vcenter-host))   # vCenter host or IP
vcenter_usr:              ((ops-man-vsphere.username))    # vCenter username. If user is tied to a domain, then escape the \, example `domain\\user`
vcenter_pwd:              ((ops-man-vsphere.password))        # vCenter password
vcenter_datacenter:       home-lab                  # vCenter datacenter
vcenter_datastore:        ssd
vcenter_ca_cert:
vcenter_insecure:         true

# Ops Manager VM configuration
om_vm_host:                                                     # Optional - vCenter host to deploy Ops Manager in
om_data_store:                  ((om-data-store))               # vCenter datastore name to deploy Ops Manager in
opsman_domain_or_ip_address:    ((om-host-name)).((subdomain))  # FQDN to access Ops Manager without protocol (will use https), ex: opsmgr.example.com
om_ntp_servers:                 ((ntp-servers))                 # Comma-separated list of NTP Servers
om_dns_servers:                 ((dns-servers))                 # Comma-separated list of DNS Servers
om_gateway:                     ((infrastructure-gateway))      # Gateway for Ops Manager network
om_netmask:                     ((om-netmask))                  # Netmask for Ops Manager network
om_ip:                          ((om-ip-address))               # IP to assign to Ops Manager VM
om_vm_network:                  ((infrastructure-network))      # vCenter network name to use to deploy Ops Manager in
om_vm_name:                     ((env-id))-ops-manager          # Name to use for Ops Manager VM
opsman_disk_type:               "thin"                          # Disk type for Ops Manager VM (thick|thin)
om_vm_power_state:              true                            # Whether to power on Ops Manager VM after creation

# vCenter Cluster or Resource Pool to use to deploy Ops Manager.
# Possible formats:
#   cluster:       /<Data Center Name>/host/<Cluster Name>
#   resource pool: /<Data Center Name>/host/<Cluster Name>/Resources/<Resource Pool Name>
om_resource_pool: /((vcenter-data-center))/host/((vcenter-cluster))/Resources/((vcenter-resource-pool-1))

ephemeral_storage_names:  ((fast-storage)),((slow-storage))        # Ephemeral Storage names in vCenter for use by PCF
persistent_storage_names: ((slow-storage)),((fast-storage))        # Persistent Storage names in vCenter for use by PCF

bosh_vm_folder: ((env-id))-pcf-vms                     # vSphere datacenter folder (such as pcf_vms) where VMs will be placed
bosh_template_folder: ((env-id))-pcf-templates     # vSphere datacenter folder (such as pcf_templates) where templates will be placed
bosh_disk_path: ((env-id))-pcf-disk                # vSphere datastore folder (such as pcf_disk) where attached disk images will be created

trusted_certificates: ''        # Trusted certificates to be deployed along with all VM's provisioned by BOSH
vm_disk_type: "thin"         # Disk type for BOSH provisioned VM. (thick|thin)

# AZ configuration for Ops Director
az_1_name:            ((vcenter-resource-pool-1))            # Logical name of availability zone. No spaces or special characters.
az_1_cluster_name:    ((vcenter-cluster))   # Name of cluster in vCenter for AZ1
az_1_rp_name:         ((vcenter-resource-pool-1))            # Resource pool name in vCenter for AZ1
az_2_name:            ((vcenter-resource-pool-2))            # Logical name of availability zone. No spaces or special characters.
az_2_cluster_name:    ((vcenter-cluster))   # Name of cluster in vCenter for AZ2
az_2_rp_name:         ((vcenter-resource-pool-2))            # Resource pool name in vCenter for AZ2
az_3_name:            ((vcenter-resource-pool-3))           # Logical name of availability zone. No spaces or special characters.
az_3_cluster_name:    ((vcenter-cluster))   # Name of cluster in vCenter for AZ3
az_3_rp_name:         ((vcenter-resource-pool-3))            # Resource pool name in vCenter for AZ3

ntp_servers:          ((ntp-servers))       # Comma-separated list of NTP servers to use for VMs deployed by BOSH
ops_dir_hostname:     ((director-host-name)).((subdomain))      # Optional DNS name for Ops Director. Should be reachable from all networks.
enable_vm_resurrector: true   # Whether to enable BOSH VM resurrector
max_threads: 30               # Max threads count for deploying VMs

# Network configuration for Ops Director
icmp_checks_enabled: false     # Enable or disable ICMP checks

infra_network_name: "INFRASTRUCTURE"
infra_vsphere_network:        ((infrastructure-network))        # vCenter Infrastructure network name
infra_nw_cidr:                ((infrastructure-cidr))           # Infrastructure network CIDR, ex: 10.0.0.0/22
infra_excluded_range:         ((infrastructure-excluded))       # Infrastructure network exclusion range
infra_nw_dns:                 ((dns-servers))         # Infrastructure network DNS
infra_nw_gateway:             ((infrastructure-gateway))              # Infrastructure network Gateway
infra_nw_azs:                 ((vcenter-resource-pool-1)),((vcenter-resource-pool-2)),((vcenter-resource-pool-3))    # Comma separated list of AZ's to be associated with this network
nsx_networking_enabled: false # (true|false) to use nsx networking feature
nsx_address:                  # address of nsx
nsx_username:                 # username for nsx access
nsx_password:                 # password for nsx access
nsx_ca_certificate:           # cert for nsx

deployment_network_name: "DEPLOYMENT"
deployment_vsphere_network:   ((deployment-network))   # vCenter Deployment network name
deployment_nw_cidr:           ((deployment-cidr))           # Deployment network CIDR, ex: 10.0.0.0/22
deployment_excluded_range:    ((deployment-excluded))   # Deployment network exclusion range
deployment_nw_dns:            ((dns-servers))         # Deployment network DNS
deployment_nw_gateway:        ((deployment-gateway))              # Deployment network Gateway
deployment_nw_azs:            ((vcenter-resource-pool-1)),((vcenter-resource-pool-2)),((vcenter-resource-pool-3))    # Comma separated list of AZ's to be associated with this network

services_network_name: "SERVICES"
is_service_network:           false                   # Required select service network option in Ops man true or false
services_vsphere_network:     ((services-network))    # vCenter Services network name
services_nw_cidr:             ((services-cidr))           # Services network CIDR, ex: 10.0.0.0/22
services_excluded_range:      ((services-excluded))   # Services network exclusion range
services_nw_dns:              ((dns-servers))         # Services network DNS
services_nw_gateway:          ((services-gateway))             # Services network Gateway
services_nw_azs:              ((vcenter-resource-pool-1)),((vcenter-resource-pool-2)),((vcenter-resource-pool-3))    # Comma separated list of AZ's to be associated with this network

dynamic_services_network_name: "DYNAMIC-SERVICES"
dynamic_services_vsphere_network: ((dynamic-network))  # vCenter Dynamic Services network name
dynamic_services_nw_cidr:         ((dynamic-cidr))      # Dynamic Services network CIDR, ex: 10.0.0.0/22
dynamic_services_excluded_range:  ((dynamic-excluded))    # Dynamic Services network exclusion range
dynamic_services_nw_dns:          ((dns-servers))     # Dynamic Services network DNS
dynamic_services_nw_gateway:      ((dynamic-gateway))          # Dynamic Services network Gateway
dynamic_services_nw_azs:          ((vcenter-resource-pool-1)),((vcenter-resource-pool-2)),((vcenter-resource-pool-3))       # Comma separated list of AZ's to be associated with this network

ert_singleton_job_az:         ((vcenter-resource-pool-1))      # AZ to use for deployment of ERT Singleton jobs
ert_errands_to_disable:       # Comma-separated list of errand names to disable before deploy

loggregator_endpoint_port:    443     # Loggegrator Port. Default is 443
company_name:                 # Company Name for Apps Manager
company_proxy_domain:         # If set to a non-empty string, bypass DNS when uploading stemcells to Ops Manager

## Syslog endpoint configuration goes here
# Optional. If syslog_host is specified, syslog_port, syslog_protocol,
# syslog_drain_buffer_size, and enable_security_event_logging must be set.
syslog_host:
syslog_port:
syslog_protocol:
enable_security_event_logging: false
syslog_drain_buffer_size: 10000

## Wildcard domain certs go here
# Optional. Will be generated if blank.
ssl_cert:
ssl_private_key:
saml_ssl_cert:
saml_ssl_private_key:

haproxy_forward_tls: disable # If enabled HAProxy will forward all requests to the router over TLS (enable|disable)
haproxy_backend_ca:         # HAProxy will use the CA provided to verify the certificates provided by the router.

# An ordered, colon-delimited list of Golang supported TLS cipher suites in OpenSSL format.
# Operators should verify that these are supported by any clients or downstream components that will initiate TLS handshakes with the Router/HAProxy.
router_tls_ciphers:  ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384       # The recommended setting is "ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".
haproxy_tls_ciphers: DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384       # The recommended setting is "DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384".

disable_http_proxy: false
security_acknowledgement: X # Must be set to 'X'. See explanation here: https://docs.pivotal.io/pivotalcf/latest/customizing/config-er-vmware.html#app-security

## TCP routing and routing services
tcp_routing: enable                    # Enable/disable TCP routing (enable|disable)
tcp_routing_ports: 1024-65535                     # A comma-separated list of ports and hyphen-separated port ranges, e.g. 52135,34000-35000,23478
route_services: enable                 # Enable/disable route services (enable|disable)
ignore_ssl_cert_verification: true     # Whether to disable SSL cert verification for this environment
garden_network_pool_cidr: 10.254.0.0/22 # Only change this if you need to avoid address collision with a third-party service on the same subnet.
garden_network_mtu: 1454                # Applications Network Maximum Transmission Unit bytes

# If smtp_address is configured, smtp_from, smtp_port, smtp_user, smtp_pwd, and
# smtp_auth_mechanism must also be set.
smtp_address:
smtp_from:
smtp_port:
smtp_user:
smtp_pwd:
smtp_auth_mechanism: none

## Authentication type needed. SAML is not presently supported.
authentication_mode: internal # (internal|ldap) If ldap, specify ldap configuration below.
ldap_url:
ldap_user:
ldap_pwd:
search_base:
search_filter:
group_search_base:
group_search_filter:
mail_attribute_name:
first_name_attribute:
last_name_attribute:

## Deployment domain names
system_domain: ((system-prefix)).((subdomain))
apps_domain:   ((apps-prefix)).((subdomain))
tcp_domain:    ((tcp-prefix)).((subdomain))

skip_cert_verify: true       # If true, disable SSL certificate verification for this environment.

disable_insecure_cookies: false # If true, disable insecure cookies on the router.

default_quota_memory_limit_mb: 10240
default_quota_max_number_services: 1000
allow_app_ssh_access: false             # Whether to allow SSH access to application instances
tcp_route_quota: 1000

router_request_timeout_in_seconds: 900

ha_proxy_ips:           # Comma-separated list of static IPs
router_static_ips:      ((router-static-ips))
tcp_router_static_ips:  ((tcp-router-static-ips))
ssh_static_ips:         ((ssh-static-ips))

mysql_monitor_email:    ((mysql-monitor-email))
mysql_backups: disable   # Whether to enable MySQL backups. (disable|s3|scp)

#SCP backup config params (leave empty values if you're not using scp)
mysql_backups_scp_server:
mysql_backups_scp_port:
mysql_backups_scp_user:
mysql_backups_scp_key:
mysql_backups_scp_destination:
mysql_backups_scp_cron_schedule:

#S3 backup config params (leave empty values if you're not using s3)
mysql_backups_s3_endpoint_url:
mysql_backups_s3_bucket_name:
mysql_backups_s3_bucket_path:
mysql_backups_s3_access_key_id:
mysql_backups_s3_secret_access_key:
mysql_backups_s3_cron_schedule:

## Default resource configuration
## these resources can take any parameter made available in
## the ops manager API ( https://<your-ops-man/docs#configuring-resources-for-a-job )
consul_server_instances: 3
nats_instances: 2
etcd_tls_server_instances: 3
nfs_server_instances: 1
mysql_proxy_instances: 2
mysql_instances: 1
backup_prepare_instances: 0
ccdb_instances: 0
diego_database_instances: 1
uaadb_instances: 0
uaa_instances: 2
cloud_controller_instances: 1
ha_proxy_instances: 0
router_instances: 1
mysql_monitor_instances: 1
clock_global_instances: 1
cloud_controller_worker_instances: 2
diego_brain_instances: 3
diego_cell_instances: 2
loggregator_traffic_controller_instances: 3
syslog_adapter_instances: 3
doppler_instances: 3
tcp_router_instances: 1

# leave nsx fields empty if you are not leveraging the nsx features for a given component
tcp_router_nsx_security_group:
tcp_router_nsx_lb_edge_name:
tcp_router_nsx_lb_pool_name:
tcp_router_nsx_lb_security_group:
tcp_router_nsx_lb_port:
router_nsx_security_group:
router_nsx_lb_edge_name:
router_nsx_lb_pool_name:
router_nsx_lb_security_group:
router_nsx_lb_port:
diego_brain_nsx_security_group:
diego_brain_nsx_lb_edge_name:
diego_brain_nsx_lb_pool_name:
diego_brain_nsx_lb_security_group:
diego_brain_nsx_lb_port:
