---

platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPS_MGR_USR:
  OPS_MGR_PWD:
  PIVNET_API_TOKEN:
  NO_PROXY:
  OM_IP:
  IAAS:

inputs:
  - name: pivnet-product
  - name: pcf-pipelines
  - name: homelab
  
run:
  path: homelab/pipelines/install-pcf/tasks/upload-product-and-stemcell/task.sh
