---

platform: linux

image_resource:
  type: docker-image
  source: {repository: starkandwayne/concourse}

params:

inputs:
  - name: homelab

outputs:
  - name: odb-releases

run:
  path: homelab/pipelines/install-pcf/tasks/config-tcp/task.sh
