---

platform: linux

image_resource:
  type: docker-image
  source: {repository: starkandwayne/concourse}

params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_PASSWORD:
  OPSMAN_USERNAME:
  SYSTEM_DOMAIN:
  TCP_DOMAIN:
  TCP_ROUTE_QUOTA: 

inputs:
  - name: homelab

outputs:
  - name: odb-releases

run:
  path: homelab/pipelines/install-pcf/tasks/config-tcp/task.sh
